In [254]:
import pandas as pd
pf = pd.read_csv('../data/presidents.csv', index_col='id')
pf['col_adjusted_base_comp'] = pf["base_comp"]/pf["cost_of_living"]

In [255]:
pf.head()

name                  photo  \
id                                              
0     Joseph A. Alutto       204796_14571.jpg   
1       Elson S. Floyd         floyd_3875.jpg   
2   Paula Allen-Meares  allen-meares_1158.jpg   
3          Renu Khator        khator_3639.jpg   
4     Robert L. Barchi       barchi_22204.jpg   

                               org_name       state  cost_of_living  \
id                                                                    
0                 Ohio State University        Ohio           0.896   
1           Washington State University  Washington           1.032   
2     University of Illinois at Chicago    Illinois           1.010   
3                 University of Houston       Texas           0.967   
4   Rutgers University at New Brunswick  New Jersey           1.145   

    start_term  base_comp  revenues_2014  days_employed_2014  \
id                                                             
0       201307     634572     2854674173                 184   
1       200705     725000      921662039                2437   
2       200901     422458     1877887288                1826   
3       200801     700000      948745952                2192   
4       201209     649624     2284387000                 487   

    tuition_fees_201415  enrollment  col_adjusted_base_comp  
id                                                           
0                 10037       58322           708227.678571  
1                 12428       28686           702519.379845  
2                 13634       27969           418275.247525  
3                  8605       40914           723888.314374  
4                 13813       48378           567357.205240

In [256]:
len(pf)

142

In [257]:
pf[["base_comp"]].mean()

base_comp    421687.485915
dtype: float64

In [258]:
pf[["base_comp"]].median()

base_comp    410146.5
dtype: float64

In [259]:
from sklearn.neighbors import NearestNeighbors
from sklearn import preprocessing
import numpy as np
initial = np.genfromtxt('../data/presidents.csv', dtype=float, delimiter=',', skip_header=1, usecols=range(7, 10))
initial[:5]

array([[  6.34572000e+05,   2.85467417e+09,   1.84000000e+02],
       [  7.25000000e+05,   9.21662039e+08,   2.43700000e+03],
       [  4.22458000e+05,   1.87788729e+09,   1.82600000e+03],
       [  7.00000000e+05,   9.48745952e+08,   2.19200000e+03],
       [  6.49624000e+05,   2.28438700e+09,   4.87000000e+02]])

In [260]:
presidents = preprocessing.normalize(initial)
presidents[:5]

array([[  2.22292264e-04,   9.99999975e-01,   6.44556907e-08],
       [  7.86622151e-04,   9.99999691e-01,   2.64413542e-06],
       [  2.24964508e-04,   9.99999975e-01,   9.72369303e-07],
       [  7.37815859e-04,   9.99999728e-01,   2.31041766e-06],
       [  2.84375622e-04,   9.99999960e-01,   2.13186286e-07]])

In [261]:
nbrs = NearestNeighbors(n_neighbors=8, algorithm='ball_tree').fit(presidents)
distances, indices = nbrs.kneighbors(presidents)
distances[:5], indices[:5]

(array([[  0.00000000e+00,   1.88630019e-06,   2.25039825e-06,
           2.82226772e-06,   5.28304739e-06,   7.06326053e-06,
           9.64841586e-06,   1.38840652e-05],
        [  0.00000000e+00,   5.47867487e-06,   8.68424075e-06,
           1.72150950e-05,   2.46371996e-05,   2.72161669e-05,
           2.81428597e-05,   2.84105110e-05],
        [  0.00000000e+00,   1.02075723e-06,   2.75890378e-06,
           2.82226772e-06,   4.23575311e-06,   4.27662870e-06,
           1.12373219e-05,   1.23346207e-05],
        [  0.00000000e+00,   5.29103440e-06,   1.42573066e-05,
           1.47215799e-05,   1.83980011e-05,   1.90233746e-05,
           3.18335335e-05,   3.48110350e-05],
        [  0.00000000e+00,   3.30454030e-06,   5.05860041e-06,
           5.17383033e-06,   1.76852413e-05,   3.96943509e-05,
           3.97435111e-05,   4.30381730e-05]]),
 array([[  0,  36,  86,   2,  39,  28,  19,  55],
        [  1, 134,  32,  93,  14, 140, 106,  82],
        [  2,  36,  39,   0,  86,  28,

In [262]:
pf["neighbors"] = indices.tolist()

pf.loc[indices[:1][0].tolist()]

name                  photo  \
id                                                   
0          Joseph A. Alutto       204796_14571.jpg   
36          Phyllis M. Wise          wise_3869.jpg   
86         Michael V. Drake          drake_546.jpg   
2        Paula Allen-Meares  allen-meares_1158.jpg   
39            Carol L. Folt       199120_10926.jpg   
28        J. Bernard Machen         machen_843.jpg   
19            Eric W. Kaler         kaler_1910.jpg   
55  Mitchell E. Daniels Jr.      daniels_22202.jpg   

                                       org_name           state  \
id                                                                
0                         Ohio State University            Ohio   
36   University of Illinois at Urbana-Champaign        Illinois   
86           University of California at Irvine      California   
2             University of Illinois at Chicago        Illinois   
39  University of North Carolina at Chapel Hill  North Carolina   
28                        University of Florida         Florida   
19          University of Minnesota-Twin Cities       Minnesota   
55          Purdue University at West Lafayette         Indiana   

    cost_of_living  start_term  base_comp  revenues_2014  days_employed_2014  \
id                                                                             
0            0.896      201307     634572     2854674173                 184   
36           1.010      201110     530501     2366647420                 823   
86           1.123      200507     392000     1775357000                3106   
2            1.010      200901     422458     1877887288                1826   
39           0.917      201307     520000     2284958065                 184   
28           0.988      200312     564553     2463049000                3684   
19           0.976      201107     610000     2868600997                 915   
55           0.914      201301     420000     1778337652                 365   

    tuition_fees_201415  enrollment  col_adjusted_base_comp  \
id                                                            
0                 10037       58322           708227.678571   
36                15020       45140           525248.514851   
86                13179       30051           349065.004452   
2                 13634       27969           418275.247525   
39                 8336       29135           567066.521265   
28                 6313       49459           571409.919028   
19                13560       51147           625000.000000   
55                10002       39752           459518.599562   

                          neighbors  
id                                   
0    [0, 36, 86, 2, 39, 28, 19, 55]  
36   [36, 2, 0, 39, 86, 28, 19, 55]  
86   [86, 0, 36, 2, 39, 19, 28, 55]  
2    [2, 36, 39, 0, 86, 28, 55, 19]  
39   [39, 28, 2, 36, 0, 86, 55, 12]  
28   [28, 39, 2, 36, 0, 55, 86, 12]  
19   [19, 43, 86, 0, 36, 2, 39, 28]  
55  [55, 12, 28, 67, 46, 39, 2, 36]

In [263]:
def neighbor_averages(ns, factor):
    return pf.loc[ns][[factor]].mean()[0]

pf['col_adjusted_neighbor_average'] =  pf["neighbors"].map(lambda x: neighbor_averages(ns=x, factor='col_adjusted_base_comp'))
pf['neighbor_average'] = pf["neighbors"].map(lambda x: neighbor_averages(x, factor='base_comp'))
pf.head()

name                  photo  \
id                                              
0     Joseph A. Alutto       204796_14571.jpg   
1       Elson S. Floyd         floyd_3875.jpg   
2   Paula Allen-Meares  allen-meares_1158.jpg   
3          Renu Khator        khator_3639.jpg   
4     Robert L. Barchi       barchi_22204.jpg   

                               org_name       state  cost_of_living  \
id                                                                    
0                 Ohio State University        Ohio           0.896   
1           Washington State University  Washington           1.032   
2     University of Illinois at Chicago    Illinois           1.010   
3                 University of Houston       Texas           0.967   
4   Rutgers University at New Brunswick  New Jersey           1.145   

    start_term  base_comp  revenues_2014  days_employed_2014  \
id                                                             
0       201307     634572     2854674173                 184   
1       200705     725000      921662039                2437   
2       200901     422458     1877887288                1826   
3       200801     700000      948745952                2192   
4       201209     649624     2284387000                 487   

    tuition_fees_201415  enrollment  col_adjusted_base_comp  \
id                                                            
0                 10037       58322           708227.678571   
1                 12428       28686           702519.379845   
2                 13634       27969           418275.247525   
3                  8605       40914           723888.314374   
4                 13813       48378           567357.205240   

                             neighbors  col_adjusted_neighbor_average  \
id                                                                      
0       [0, 36, 86, 2, 39, 28, 19, 55]                  527976.435657   
1   [1, 134, 32, 93, 14, 140, 106, 82]                  415544.291226   
2       [2, 36, 39, 0, 86, 28, 55, 19]                  527976.435657   
3     [3, 47, 111, 33, 61, 89, 93, 74]                  466293.630910   
4    [4, 114, 56, 71, 100, 46, 67, 12]                  459530.880914   

    neighbor_average  
id                    
0         511760.500  
1         402006.125  
2         511760.500  
3         444687.750  
4         452670.875

In [264]:
import json
pf.to_json(orient='records')

'[{"name":"Joseph A. Alutto","photo":"204796_14571.jpg","org_name":"Ohio State University","state":"Ohio","cost_of_living":0.896,"start_term":201307,"base_comp":634572,"revenues_2014":2854674173,"days_employed_2014":184,"tuition_fees_201415":10037,"enrollment":58322,"col_adjusted_base_comp":708227.6785714286,"neighbors":[0,36,86,2,39,28,19,55],"col_adjusted_neighbor_average":527976.4356569655,"neighbor_average":511760.5},{"name":"Elson S. Floyd","photo":"floyd_3875.jpg","org_name":"Washington State University","state":"Washington","cost_of_living":1.032,"start_term":200705,"base_comp":725000,"revenues_2014":921662039,"days_employed_2014":2437,"tuition_fees_201415":12428,"enrollment":28686,"col_adjusted_base_comp":702519.3798449612,"neighbors":[1,134,32,93,14,140,106,82],"col_adjusted_neighbor_average":415544.291226324,"neighbor_average":402006.125},{"name":"Paula Allen-Meares","photo":"allen-meares_1158.jpg","org_name":"University of Illinois at Chicago","state":"Illinois","cost_of_liv